#ifndef X86TERM_INTERRUPT_HANDLERS_H
#define X86TERM_INTERRUPT_HANDLERS_H

void isr0(void);
void isr1(void);
void isr2(void);
void isr3(void);
void isr4(void);
void isr5(void);
void isr6(void);
void isr7(void);
void isr8(void);
void isr9(void);
void isr10(void);
void isr11(void);
void isr12(void);
void isr13(void);
void isr14(void);
void isr15(void);
void isr16(void);
void isr17(void);
void isr18(void);
void isr19(void);
void isr20(void);
void isr21(void);
void isr22(void);
void isr23(void);
void isr24(void);
void isr25(void);
void isr26(void);
void isr27(void);
void isr28(void);
void isr29(void);
void isr30(void);
void isr31(void);
void isr32(void);
void isr33(void);
void isr34(void);
void isr35(void);
void isr36(void);
void isr37(void);
void isr38(void);
void isr39(void);
void isr40(void);
void isr41(void);
void isr42(void);
void isr43(void);
void isr44(void);
void isr45(void);
void isr46(void);
void isr47(void);

#endif
